name: Thelma
version: 1.3
date: 2022-03-03
description: |
    THreshold ELements, Modeling and Applications

authors:
    - name: Victor Bovdi
      url: mailto:vbovdi@gmail.com
    - name: Vasyl Laver
      url: mailto:vasyl.laver@uzhnu.edu.ua

maintainers:
    - name: Vasyl Laver
      url: mailto:vasyl.laver@uzhnu.edu.ua

GAP: ">= 4.10"

needed-pkgs:
    - name: "GAPDoc"
      version: "1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "Gauss"
      version: "2018.09.08"
      url: "https://homalg-project.github.io/pkg/Gauss"

www: https://gap-packages.github.io/Thelma
readme: README.md
packageinfo: https://gap-packages.github.io/Thelma/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/Thelma/releases/download/v1.3/Thelma-1.3.tar.gz

abstract: |
    The <span class="pkgname">Thelma</span> package is package with algorithms to deal with threshold elements.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    threshold elements, neural networks, threshold logic.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BL22</span>]   <b class='BibAuthor'>Bovdi, V. and Laver, V.</b>,
     <i class='BibTitle'>Thelma, THreshold ELements, Modeling and Applications,
             Version 1.3</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/Thelma">https://gap-packages.github.io/Thelma</a></span>.
    </p>
    

bibtex: |
    @misc{ Thelma1.3,
      author =           {Bovdi, V. and Laver, V.},
      title =            {{Thelma},    THreshold    ELements,    Modeling    and
                          Applications, {V}ersion 1.3},
      month =            {Mar},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href          {https://gap-packages.github.io/Thelma}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{Thelma}}},
      keywords =         {threshold elements; neural networks; threshold logic},
      printedkey =       {BL22}
    }

